work/forum/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView,LogoutView

app_name ='forum'
urlpatterns = [
    path('',views.UserFormView.as_view(),name='register'),
    path('<int:pk>/',views.DetailView.as_view(), name='detail'),

    path('about',views.AboutView,name='about'),

    path('intern/list',views.InternsView.as_view(),name='interns'),
    path('intern/add/',views.InternCreate.as_view(),name='intern-add'),
    path('intern/<int:pk>',views.InternView.as_view(), name='intern'),
    path('intern/<int:pk>/upload',views.FileFormView.as_view(), name='upload'),
    path('intern/<int:pk>/add_comment',views.AddComent.as_view(), name='add-comment'),
    path('intern/<int:comment_id>/delete', views.DeleteComment.as_view(), name='delete-comment'),
    path('intern/<int:comment_id>/like', views.VoteComment.as_view(), name='vote-comment'),
    path('intern/<int:pk>/edit',views.InternUptade.as_view(),name='intern-update'),
    path('intern/<int:pk>/delete',views.InternDelete.as_view(),name='intern-delete'),
    path('intern/<int:pk>/vote',views.vote,name='vote'),
    path('intern/<int:pk>/accept', views.accept, name='accept'),

    path('login/',views.loginview, name='login'),
    path('departments', views.DepartmentView.as_view(), name='departments'),
    path('search',views.search_view,name='search'),
    path('logout',views.logoutview, name='logout'),
    path('profile/',views.profile,name='profile'),
    path('calendar',views.CalendarView.as_view(),name='calendar'),
    path('calendar/new_event',views.EventFormView.as_view(),name='add-event'),
]

work/work/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib.auth.views import LoginView,LogoutView
#from work.forum import views as forum_views
urlpatterns = [
    path('forum/', include('forum.urls')),

    path('admin/', admin.site.urls),
    #path('login/', forum_views.loginview, name='login'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

work/forum/models.py
from __future__ import unicode_literals
import datetime
from datetime import timezone, timedelta
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from .validators import validate_file_extension


# Create your models here
class Department(models.Model):
    department_name = models.CharField(max_length=250)
    dep_logo = models.FileField()

    def __str__(self):
        return self.department_name

    def get_absolute_url(self):
        return reverse('forum:detail', kwargs={'pk': self.pk})


class Advisor(models.Model):
    user = models.OneToOneField(
        User,
        default=None,
        null=True,
        on_delete=models.CASCADE)
    advisor_name = models.CharField(max_length=250)
    phone_number = models.CharField(max_length=250)
    advisor_department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('forum:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.advisor_name


class Intern(models.Model):
    Rating_CHOICES = (
        (1, 'Poor'),
        (2, 'Average'),
        (3, 'Good'),
        (4, 'Very Good'),
        (5, 'Excellent')
    )
    technical_skills = models.IntegerField(choices=Rating_CHOICES, default=1)
    experience = models.IntegerField(choices=Rating_CHOICES, default=1)
    team_work = models.IntegerField(choices=Rating_CHOICES, default=1)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    advisor = models.ForeignKey(Advisor, on_delete=models.CASCADE)
    app_date = models.DateTimeField('date applied', auto_now_add=True, blank=True)
    votes = models.IntegerField(default=0)
    is_favourite = models.BooleanField(default=False)
    is_accepted = models.IntegerField(default=0)
    profile_photo = models.ImageField(default="default-picture_0_0.png", null=True, blank=True)
    inter_date = models.DateField(
        max_length=10,
        help_text="format : YYYY-MM-DD",
        null=True)
    resume = models.FileField(validators=[validate_file_extension])

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('forum:interns')




class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default-picture_0_0.png', null=True, blank=True)
    department = models.ForeignKey(Department, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} Profile'


class Appointment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    intern = models.OneToOneField(Intern, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    start_time = models.DateTimeField()
    complete = models.BooleanField(default=False)

    def __str__(self):
        if self.intern.is_accepted == 0:
            url = reverse('forum:intern', args=(self.intern.id,))
            return f'Appointment with <a href="{url}">{self.intern.name}  </a> <strong> {self.user.username}<strong>'
        else:
            return f'Interview with {self.intern.name} has done.'

    def get_absolute_url(self):
        return reverse('forum:calendar')


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    intern = models.ForeignKey(Intern, on_delete=models.CASCADE)
    text = models.TextField(max_length=160)
    like = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.text} --by{self.user.username}'


class File(models.Model):
    file = models.FileField()
    intern = models.ForeignKey(Intern, on_delete=models.CASCADE)

work/forum/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Intern, Appointment, Comment, File
from django.forms import DateInput


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class SearchForm(forms.ModelForm):
    class Meta:
        model = Intern
        fields = ['name']


class EventForm(forms.ModelForm):
    class Meta:
        model = Appointment
        widgets = {
            'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        exclude = ['user']

    def __init__(self, user, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)

        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['intern'].queryset = Intern.objects.filter(is_accepted=0)
        self.user = user

    def save(self, commit=True):
        instance = super().save(False)
        instance.user = self.user
        instance.save(commit)
        return instance


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ['file']

work/forum/views.py
from django.shortcuts import render
from django.utils import timezone
from django.contrib import messages
# Create your views here.
from django.views import generic
from datetime import datetime
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Intern, Advisor, Department
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.views.generic import View
from .forms import UserForm, SearchForm, EventForm, CommentForm, FileForm
from django.contrib.auth.models import Permission, User
from django.utils.safestring import mark_safe
from .models import *
from .utils import Calendar
import calendar
from django.core.files.storage import FileSystemStorage


class DetailView(generic.DetailView):
    model = Department
    template_name = 'forum/detail.html'


def AboutView(request):
    return render(request, 'forum/about.html', {})





class InternView(generic.DetailView):
    model = Intern
    template_name = 'forum/intern.html'

    # def get_context_data(self, **kwargs):
    # context = super(InternView, self).get_context_data(**kwargs)
    # context['comments'] = Comment.objects.filter(intern=self.object)


class DepartmentView(generic.ListView):
    model = Department
    template_name = 'forum/department.html'
    context_object_name = 'department_list'

    def get_queryset(self):
        return Department.objects.all()


# @method_decorator(login_required(login_url='forum:login'), name='dispatch')
class InternsView(LoginRequiredMixin, generic.ListView):
    login_url = 'forum:login'
    template_name = 'forum/interns.html'
    context_object_name = 'intern_list'

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query:
            intern_list = Intern.objects.filter(name__icontains=query)
        else:
            intern_list = Intern.objects.order_by('-votes')

        return intern_list


@method_decorator(login_required(login_url='forum:login'), name='dispatch')
class InternCreate(CreateView):
    model = Intern
    fields = ['department', 'name', 'advisor', 'profile_photo', 'resume', 'technical_skills', 'team_work', 'experience']


class InternUptade(UpdateView):
    model = Intern
    fields = ['department', 'name', 'advisor', 'profile_photo', 'resume']


class InternDelete(DeleteView):
    model = Intern
    success_url = reverse_lazy('forum:interns')


class UserFormView(View):
    form_class = UserForm
    template_name = 'forum/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)
            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('forum:departments')

        return render(request, self.template_name, {'form': form})


def loginview(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                if user .is_superuser:
                    return redirect('forum:interns')
                else:
                    return redirect('forum:about')
            else:
                return render(request, 'forum/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'forum/login.html', {'error_message': 'Invalid login'})
    return render(request, 'forum/login.html')


def logoutview(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'forum/login.html', context)


def vote(request, pk):
    intern = Intern.objects.get(pk=pk)
    intern.votes += 1
    intern.save()
    return redirect('forum:interns')


def accept(request, pk):
    intern = Intern.objects.get(pk=pk)
    intern.is_accepted = 1
    intern.save()
    return redirect('forum:interns')


@login_required
def profile(request):
    return render(request, 'forum/profile.html')


@login_required
def search_view(request):
    interns = Intern.objects.all()
    form = SearchForm(request.GET)

    if form.is_valid():
        if form.cleaned_data["q"]:
            interns = interns.filter(name_startswith=form.cleaned_data["q"])
        elif form.cleaned_data["name"]:
            interns = interns.filter(name_startswith=form.cleaned_data["name"])

    return render(request, "forum/search.html", {"form": form, "intern_list": interns})


class CalendarView(generic.ListView):
    model = Appointment
    template_name = 'forum/calendar.html'

    def get_queryset(self):
        return Appointment.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(d.year, d.month, withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return datetime.date(year, month, day=1)
    return datetime.date.today()


def prev_month(d):
    first = d.replace(day=1)
    prev = first - timedelta(days=1)
    month = 'month=' + str(prev.year) + '-' + str(prev.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next = last + timedelta(days=1)
    month = 'month=' + str(next.year) + '-' + str(next.month)
    return month


class EventFormView(View):
    form_class = EventForm
    template_name = 'forum/event_form.html'

    def get(self, request, event_id=None):
        instance = Appointment()
        user = self.request.user
        form = self.form_class(user, None, instance=instance)
        return render(request, self.template_name, {'form': form})

    def post(self, request, event_id=None):
        instance = Appointment()
        user = self.request.user
        form = self.form_class(user, request.POST, instance=instance)
        if form.is_valid():
            form.save()
        else:
            return render(request, self.template_name, {'form': form})

        return HttpResponseRedirect(reverse('forum:calendar'))


class FileFormView(View):

    def get(self, request):
        return render(request, 'intern.html', {})

    def post(self, request, pk):
        uploaded_file = request.FILES['document']
        """fs = FileSystemStorage()
        name=fs.save(uploaded_file.name,uploaded_file)
        url = fs.url(name)"""
        File.objects.create(
            intern_id=pk,
            file=uploaded_file
        )
        return redirect('forum:intern', pk=pk)


class AddComent(View):

    def get(self, request, pk):
        return redirect('forum:intern', pk=pk)

    def post(self, request, pk):
        text = request.POST['textcomment']
        this = Intern.objects.get(pk=pk)
        Comment.objects.create(intern_id=pk, text=text, user_id=request.user.id)

        return redirect('forum:intern', pk=pk)


class DeleteComment(View):
    def get(self, comment_id):
        comment = Comment.objects.get(pk=comment_id)
        return redirect('forum:intern', pk=comment.intern.pk)

    def post(self, request, comment_id):
        print(comment_id)
        comment = Comment.objects.get(pk=comment_id)
        comment.delete()
        return redirect('forum:intern', pk=comment.intern.pk)


class VoteComment(View):
    def get(self, request, comment_id):
        comment = Comment.objects.get(pk=comment_id)
        comment.like += 1
        comment.save()
        return redirect('forum:intern', pk=comment.intern.pk)

    def post(self, request, comment_id):
        comment = Comment.objects.get(pk=comment_id)
        comment.like += 1
        comment.save()
        return redirect('forum:intern', pk=comment.intern.pk)


class SearchView(generic.ListView):
    template_name = 'forum/interns.html'
    model = Intern

    def get_queryset(self):
        try:
            name = self.kwargs['name']
        except:
            name = ''
        if (name != ''):
            object_list = self.model.objects.filter(name__icontains=name)
        else:
            object_list = self.model.objects.all()
        return object_list

work/forum/templates/forum/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>INTERNet</title>
    {% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'forum/style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'forum/button.css' %}">
<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'forum/formstyle.css' %}">
<link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.min.css">
<meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script type="text/javascript" src="{{ STATIC_URL }} /static/jquery-3.4.1.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
    {% block extrahead %}{% endblock %}
</head>
<body>

    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'forum:login' %}"><span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp;INTERNet</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">

                 {% if request.user.is_superuser%}
                     <li class="{% block interns_active %}{% endblock %}"><a href="{% url 'forum:interns'  %}"><span class="glyphicon glyphicon-education" aria-hidden="true"></span>&nbsp; Applied Interns</a></li>

                 <li>
                    <a href="{% url 'forum:intern-add' %}">
                        Add Application
                    </a>
                </li>

                    <form class="navbar-form navbar-right" role="search" method="get" action="{% url 'forum:search' %}">
                        <div class="form-group">
                            <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                        </div>
                        <button type="submit" class="btn btn-default">Search</button>
                    </form>
                {% endif %}
            </ul>

            {% if request.user.is_authenticated %}

                <ul class="nav navbar-nav navbar-right">
                     {% if request.user.is_superuser%}
                    <li>
                        <a href="{% url 'forum:profile'  %}">&nbsp; Profile</a>
                    </li>
                     <li>
                        <a class="nav-link p-0" href="#">
                          <img src="{{request.user.userprofile.image.url}}" class="rounded-circle z-depth-0"
                              alt="avatar image" height="35">
                         </a>
                    </li>
                      {% endif %}
                    <li>
                        <a href="{% url 'forum:logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>

                </ul>

            {%endif%}
        </div>

    </div>
</nav>







{% block body %}
{%endblock%}
</body>
</html>

work/forum/templates/forum/calendar.html
{% extends 'forum/base.html' %}
 {% load static %}
    {% block extrahead %}
        <link rel="stylesheet" href="{% static 'forum/calendar.css' %}">
    {% endblock %}
{% block body%}
  <div class="clearfix">
	<a class="btn btn-info left" href="{% url 'forum:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-info right" href="{% url 'forum:calendar' %}?{{ next_month }}"> Next Month </a>
	<a class="btn btn-info right" href="{% url 'forum:add-event' %}"> New Event </a>
</div>
{{ calendar }}
{% endblock %}

work/forum/templates/forum/intern.html
{%extends 'forum/base.html'%}
 {% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% block extrahead %}
        <link rel="stylesheet" href="{% static 'forum/card.css' %}">

{% endblock %}
{% block body %}
<div class="container-fluid songs-container">
    <div class="row">


            <div class="col-sm-4 col-md-3">
                <div class="panel panel-warning">
                    <div class="panel-body">

                            {% if intern.profile_photo %}
                                <img src="{{ intern.profile_photo.url}}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}

                        <h1>{{ intern.name }} </h1>
                        <h1><small>{{ intern.department }}</small></h1>
                        <h4><strong>Advisor:</strong>{{intern.advisor}}</h4>

                    </div>

                </div>
            </div>

        <!-- Right Song Info -->
            <div class="col-sm-8 col-md-9">
                <ul class="nav nav-pills" style="margin-bottom: 10px;">
                        <li role="presentation" class="active"><a href="{% url 'forum:interns' %}">View All</a><br>
                        </li>
                    </ul>


                <div class="panel panel-default" >
                    <div class="panel-body">

                        <h3>          Details</h3>

                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}

                        <table class="table">
                            <thead>
                            <tr class="warning">

                                <th>Resume</th>
                                <th>Situation</th>
                                <th>Team Work</th>
                                <th>Technical Skill</th>
                                <th>Experience</th>

                            </tr>
                            </thead>
                            <tbody>
                                <tr class="warning">
                                    <td>
                                        <a href="{{intern.resume.url}}" class="btn btn-warning btn-sm" role="button">Resume</a>
                                    </td>
                                    <td>
                                        {% if intern.is_accepted == 1 %}
                                            <h4>Accepted</h4>
                                        {% elif intern.is_accepted == 2 %}
                                            <h4>Denied</h4>
                                        {% else %}
                                            <h4>Waiting</h4>

                                        {% endif %}
                                    </td>
                                    <td>
                                        <h4>{{intern.team_work}} <span class="glyphicon glyphicon-star"></span> </h4>
                                    </td>
                                    <td>
                                        <h4>{{intern.experience}} <span class="glyphicon glyphicon-star"></span> </h4>

                                    </td>
                                    <td>
                                        <h4>{{intern.technical_skills}} <span class="glyphicon glyphicon-star"></span></h4>
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                        <br>
                        <br>
            <div class="col-sm-5 col-md-9">
                    <div class="panel panel-warning">
                        <div class="panel-body-comment">
                            <table class="comment-table">
                                <thead>
                                <tr class="info">
                                    <h3>Comments - Interview Notes</h3>
                                </tr>
                                </thead>
                                <tbody>
                                <tr class="info">
                                    <div class="main-comment-section">
                                         {% for comment in object.comment_set.all%}
                                          <ul>
                                            <li style="list-style:none">

                                        <blockquote class="blockquote">
                                         <p class="mb-0"> {{comment.text}}</p>
                                         <footer class="blockquote-footer">by<cite title="Source Title">{{comment.user.username}}</cite></footer>

                                        </blockquote>
                                                 <form action="/forum/intern/{{comment.id}}/delete" method="post" style="display: inline;">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="comment_id" value="{{ comment.id }}" />
                                                    <button type="submit" class="btn btn-default btn-sm">
                                                        <span class="glyphicon glyphicon-trash"></span>
                                                    </button>
                                                </form>
                                                <a href="{% url 'forum:vote-comment' comment.id %}" class="btn btn-danger btn-sm" role="button"> <i class="fa fa-thumbs-up"></i> {{comment.like}}</a>

                                            </li>
                                          </ul>
                                        {%endfor%}
                                     </div>

                                    <form action="/forum/intern/{{ intern.id }}/add_comment" method="post" enctype="multipart/form-data">
                                        {%csrf_token%}
                                        <input type="text" name="textcomment">
                                        <button class="btn btn-warning btn-sm" type="submit">Add Comment</button>
                                    </form>

                                </tr>

                                </tbody>
                            </table>
                        </div>
                    </div>
                    </div>
                    </div>
                </div>
                 {% if object.file_set.count == 0%}
                    <form action="/forum/intern/{{ intern.id }}/upload" method="post" enctype="multipart/form-data">
                    {%csrf_token%}
                    <input type="file" name="document">
                    <button class="btn btn-warning btn-sm" type="submit">Upload File</button>
                </form>

                {%else%}
                <div>
                    {% for the in object.file_set.all%}
                        <ul class="links">
                            <a href="{{the.file.url}}" class="button-ass" role="button">Assignment </a>

                        </ul>

                    {% endfor %}
                </div>
                {% endif %}



                 <ul class="nav nav-pills" style="margin-bottom: 10px;">
                     {%if user.is_superuser%}
                        {% if intern.is_accepted == 0 %}
                            <li role="presentation" ><a href="{% url 'forum:accept' intern.id %}" class="button-ass" role="button">Accept</a>
                            </li>
                        {%endif%}
                     {%endif%}

                 </ul>

            </div>

    </div>

</div>
{%endblock%}

work/forum/templates/forum/interns.html
{%extends 'forum/base.html'%}
 {% load static %}
 {% block extrahead %}
        <link rel="stylesheet" href="{% static 'forum/card.css' %}">
    {% endblock %}
{% block body %}
<div class="albums-container container-fluid">


    <div class="row">
        <div class="col-sm-12">
        {% if intern_list %}
            {% for intern in intern_list %}
                    <div class="card">

                        <div class="thumbnail">
                            <a href="{% url 'forum:intern' intern.id %}">
                                <img src="{{ intern.profile_photo.url }}"  class="img-responsive">
                            </a>
                            <div class="context">
                                <h3>{{intern.name}}</h3>
                                <!-- View Details -->
                                <a href="{% url 'forum:intern' intern.id %}" class="btn btn-danger btn-sm" role="button">View Details</a>
                                {%if user.is_superuser%}

                                      <a href="{% url 'forum:vote' intern.id %}" class="btn btn-danger btn-sm" role="button"> <i class="fa fa-thumbs-up"></i> {{intern.votes}}</a>
                                    <!-- Delete Album -->
                                    <form action="{% url 'forum:intern-delete' intern.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="intern_id" value="{{ intern.id }}" />
                                        <button type="submit" class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-trash"></span>
                                        </button>
                                    </form>
                                {%endif%}
                            </div>
                        </div>
                    </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}

            {% endfor %}
        {% else %}
             <p>There isn't any interns yet</p>
        {% endif %}
        </div>
    </div>
</div>

{%endblock%}